### ISSUE TITLE
Broken since most recent patch (October 22nd)

### ISSUE THREAD

**Issue by felix0908** [Baiker000/NoDeathPenaltyNineSols#1]
It's broken for me anyways, wondering if anyone else can confirm it.

**Comment by Baiker000** [comment]
It's BepInEx not loading after update because of  [assembly stripping](https://hackmd.io/@ghorsington/rJuLdZTzK)
You need correct unstripped files to run it. I uploaded them to [mod page](https://www.nexusmods.com/ninesols/mods/5)
